<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="IRCBot.Default" %>
<% if(IsIRCServer()) { %>
<% } else {%>
<!DOCTYPE html>
<html>
<head>
    <title></title>
	<meta charset="utf-8" />
    <script type="text/javascript" src="/js/Common.js"></script>
    <script type="text/javascript" src="/JS/myRequest.js"></script>

    <link rel="stylesheet" href="../TreeElement/myTreeView.css" type="text/css">
    <script type="text/javascript" src="../TreeElement/myTreeView.js"></script>
    <script type="text/javascript" src="../SignalRChat/Scripts/IRC/Chaturbate/Chaturbate.js"></script>

    <link rel="stylesheet" href="../MyIsapi/normal.css" type="text/css">
    <link rel="stylesheet" href="../MyIsapi/gradient.css" type="text/css" />
    <style>
        .sendButton {
            float: right;
	        padding:5px;
	        cursor: pointer;
        }
        .sendButton:hover {
	        background: #cccccc;
	        background: -moz-linear-gradient(top, #cccccc, #FFFFFF);
	        background: -webkit-gradient(linear, left top, left bottom, 
				        color-stop(0%,#cccccc), color-stop(100%,#FFFFFF));
	        background: -webkit-linear-gradient(top, #cccccc, #FFFFFF);
	        background: -o-linear-gradient(top, #cccccc, #FFFFFF);
	        background: -ms-linear-gradient(top, #cccccc, #FFFFFF);
	        background: linear-gradient(top, #cccccc, #FFFFFF);
	        -moz-border-radius: 5px;
	        -webkit-border-radius: 5px;
	        border-radius: 5px;
        }
        .messages {
            overflow:auto;
            background-color:#F8F8FF/*lightgray*/
        }
    </style>

    <!--Reference the autogenerated SignalR hub script.
    <script type='text/javascript' src="signalr/hubs"></script> -->
</head>
<body style="margin-top:0px;margin-bottom:0px">
    <div id="messages">
        <!--<div id="messagesList" style="display:none">empty</div>-->
        <div id="messagesList2" style="display:none;">
            <div id="messagesList3" class="messages">
                <span id="messagesListClear" class="sendButton" title="Clear messages">X</span>
                <div id="messagesList"></div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        document.getElementById("messagesList3").style.height = (document.body.clientHeight / 2) + 'px';
        document.getElementById("messages").appendChild(myTreeView.createBranch({
            name: "Messages",
            params: {
                createBranch: function () {
                    return document.getElementById('messagesList2');
                }
            }
        }));
        document.getElementById('messagesListClear').onclick = function (event) {
            consoleLog('messagesListClear');
            document.getElementById('messagesList').innerHTML = '';
            $.connection.chatHub.server.messagesListClear();
        }
        function resizerX(resizerID, mousemove) {
        }
    </script>
    <div id="eventLog"></div>
    <div id="IRCServers"></div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.6.4.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script src="Scripts/IRCBot.js"></script>
    <script type='text/javascript' src="../SignalRChat/Scripts/Default.js"></script>
    <script type='text/javascript' src="../SignalRChat/Scripts/IRCChat.js"></script>
    <!--<script type='text/javascript' src="../SignalRChat/Scripts/IRCServer.js"></script>-->
    <script src="/JS/WebRTC/DetectRTC.js"></script>
    <script type="text/javascript">
        loadScript("../SignalRChat/lang/" + getLanguageCode() + ".js", function () {
            loadScript("../SignalRChat/lang/IRC/" + getLanguageCode() + ".js", function () {  });
        });
    </script>
    <script type="text/javascript">
        document.getElementById("eventLog").appendChild(myTreeView.createBranch({
            name: "Event Log",
            params: {
                createBranch: function () {
                    var el = document.createElement("div");
                    el.innerHTML = getSynchronousResponse('Scripts/EventLog/eventLog.html');
                    return el;
                },
                onOpenBranch: function (a) { loadScript("Scripts/EventLog/EventLog.js"); }
            }
        }));
    </script>
</body>
</html>
<% } %>
