//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRCBotMessage
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string ServerHostname { get; set; }
        public string Nick { get; set; }
        public byte MessageType { get; set; }
        public string Message { get; set; }
        public string ErrorId { get; set; }
        public string Channel { get; set; }
    }
}
