//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIRCNS
    {
        public int Id { get; set; }
        public string URL { get; set; }
        public Nullable<short> Port { get; set; }
        public string Nick { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public Nullable<short> MaxConnections { get; set; }
        public Nullable<int> NextConnectionDelay { get; set; }
        public Nullable<bool> NickServSupport { get; set; }
    }
}
