//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBIRCMessage
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public int DBIRCChatsId { get; set; }
        public int DBIRCUsersId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual DBIRCChat DBIRCChat { get; set; }
        public virtual DBIRCUser DBIRCUser { get; set; }
    }
}
