//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBRooms()
        {
            this.DBConnections = new HashSet<DBConnection>();
        }
    
        public int Id { get; set; }
        public string RoomName { get; set; }
        public Nullable<System.Guid> PrivateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBConnection> DBConnections { get; set; }
    }
}
