//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBUser()
        {
            this.Connections = new HashSet<DBConnection>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.Guid BrowserID { get; set; }
        public Nullable<byte> GenderId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string AboutMe { get; set; }
        public string Location { get; set; }
        public short TimezoneOffset { get; set; }
        public bool IsMobileDevice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBConnection> Connections { get; set; }
        public virtual DBPosition DBPosition { get; set; }
    }
}
