//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatContainer : DbContext
    {
        public ChatContainer()
            : base("name=ChatContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBUser> DBUsers { get; set; }
        public virtual DbSet<DBConnection> DBConnections { get; set; }
        public virtual DbSet<DBRooms> DBRooms { get; set; }
        public virtual DbSet<DBPosition> DBPositions { get; set; }
        public virtual DbSet<DBCoords> DBCoords { get; set; }
        public virtual DbSet<DBIRCServers> DBIRCServers { get; set; }
        public virtual DbSet<DBIRCChats> DBIRCChats { get; set; }
        public virtual DbSet<DBIRCUsers> DBIRCUsers { get; set; }
        public virtual DbSet<DBIRCMessages> DBIRCMessages { get; set; }
        public virtual DbSet<ViewRoomList> ViewRoomLists { get; set; }
        public virtual DbSet<ViewRoom> ViewRooms { get; set; }
        public virtual DbSet<DBIRCGroups> DBIRCGroups { get; set; }
    }
}
