//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBCoords
    {
        public int Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double Accuracy { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<double> AltitudeAccuracy { get; set; }
        public Nullable<double> Heading { get; set; }
        public Nullable<double> Speed { get; set; }
    
        public virtual DBPosition DBPosition { get; set; }
    }
}
