//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBConnection
    {
        public int Id { get; set; }
        public string ConnectionID { get; set; }
        public int UserId { get; set; }
        public int DBRoomsId { get; set; }
    
        public virtual DBUser User { get; set; }
        public virtual DBRooms DBRoom { get; set; }
    }
}
