//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBIRCNS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBIRCNS()
        {
            this.DBIRCCS = new HashSet<DBIRCCS>();
        }
    
        public int Id { get; set; }
        public int DBIRCNSUsersId { get; set; }
        public int DBIRCNSPasswordsId { get; set; }
        public int DBIRCNSEmailsId { get; set; }
        public int DBIRCServersId { get; set; }
        public Nullable<short> MaxConnections { get; set; }
        public Nullable<int> NextConnectionDelay { get; set; }
        public Nullable<bool> NickServSupport { get; set; }
    
        public virtual DBIRCNSUsers DBIRCNSUser { get; set; }
        public virtual DBIRCNSPasswords DBIRCNSPassword { get; set; }
        public virtual DBIRCNSEmails DBIRCNSEmail { get; set; }
        public virtual DBIRCServers DBIRCServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBIRCCS> DBIRCCS { get; set; }
    }
}
