//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBIRCServers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBIRCServers()
        {
            this.DBIRCChats = new HashSet<DBIRCChats>();
            this.DBIRCUsers = new HashSet<DBIRCUsers>();
        }
    
        public int Id { get; set; }
        public string URL { get; set; }
        public Nullable<short> Port { get; set; }
        public string Name { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public int DBIRCGroupsId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBIRCChats> DBIRCChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBIRCUsers> DBIRCUsers { get; set; }
        public virtual DBIRCGroups DBIRCGroup { get; set; }
    }
}
