//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBIRCUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBIRCUsers()
        {
            this.DBIRCMessages = new HashSet<DBIRCMessages>();
        }
    
        public int Id { get; set; }
        public string Nick { get; set; }
        public int DBIRCServersId { get; set; }
    
        public virtual DBIRCServers DBIRCServer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBIRCMessages> DBIRCMessages { get; set; }
    }
}
