//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBIRCCS
    {
        public int Id { get; set; }
        public int DBIRCCSChannelsId { get; set; }
        public int DBIRCNSId { get; set; }
        public int DBIRCCSTopicsId { get; set; }
        public int DBIRCNSPasswordsId { get; set; }
    
        public virtual DBIRCCSChannels DBIRCCSChannel { get; set; }
        public virtual DBIRCNS DBIRCN { get; set; }
        public virtual DBIRCCSTopics DBIRCCSTopic { get; set; }
        public virtual DBIRCNSPasswords DBIRCNSPassword { get; set; }
    }
}
