//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBPosition
    {
        public int Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual DBUser DBUser { get; set; }
        public virtual DBCoords DBCoord { get; set; }
    }
}
