//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRoom
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int DBRoomsId { get; set; }
        public string RoomName { get; set; }
        public int Id { get; set; }
        public string ConnectionID { get; set; }
        public System.Guid BrowserID { get; set; }
        public Nullable<System.Guid> PrivateID { get; set; }
        public Nullable<byte> GenderId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string AboutMe { get; set; }
        public Nullable<int> PositionId { get; set; }
    }
}
