//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRoomList
    {
        public int DBRoomsId { get; set; }
        public string RoomName { get; set; }
        public int RoomNameCount { get; set; }
        public Nullable<System.Guid> PrivateID { get; set; }
    }
}
