var g_country="",g_city="",g_category="",g_language="",g_player="",g_wait=!1,g_reqAddTVChannels=null,g_OpenTVPlayer=!1,g_TVChannelIDRC="",g_TVChannelID="",g_cancelRemote="",g_reqRemote=null,g_reqGetDescription=null,g_reqFavorite=null,g_reqAddFavorites=null,g_guid="",g_stopAddingTVchannels=!1,g_FindTVChannels="",g_nexTVChannelID=0,g_callbackAddTVChannels=null,g_TVChannelsTableRowsLength=0,g_clicked_TVchannel=null,g_imgWaitCircle='<img src="WaitGif/WaitCircle.gif" style="width:16px; height:16px">';
function IsWaitTVChannels(){return g_wait}function AddRemoteColumn(){if(""!=g_guidRemote){var a=document.getElementById("ChannelsTable");if(null!=a)for(i=0;i<a.rows.length;i++){var c=a.rows[i].cells[1];if("undefined"==typeof c)break;if(0==i&&"R"!=c.id)return;c.style.display=""}a=document.getElementById("DivGUIDRemote");null==a?ErrorMessage("DivGUIDRemote == null"):a.innerHTML=g_guidRemote}}
function MessageElement(a){var c=document.getElementById("Message");null!=c&&c.innerHTML!=a&&(c.innerHTML=a)}
function processStatus200(a){-1!=a.responseText.indexOf("parent.")&&ErrorMessage(a.responseText);response=a.responseXML.documentElement;if(null==response)ErrorMessage("response == null"),XMLHttpRequestStop(),XMLHttpRequestStart(GetGuidRemoteArgument());else if(a=GetResponseItem("message"),""!=a&&"ping"!=a)MessageElement(a),AbortRemoteControl();else if(MessageElement(""),""!=GetResponseItem("RCMode"))RestoreRCButtons();else if(a=GetResponseItem("AddFavorites"),""!=a)"Not detected"==a?alert("New favourites from another browser is not detected"):
"Success"==a?(ToogleFavorites(!0),alert(g_strSuccessFavorite)):ErrorMessage('Unknown status "'+a+'" of adding of favorites');else if(a=GetResponseItem("Favorite"),""!=a){var c="F"+parseInt(a);a=document.getElementById(c);var b=document.getElementById("F"+c);null!=a&&"IMG"==a.nodeName||null!=b&&"IMG"==b.nodeName?(c="",c="Added"==GetResponseItem("Mode")?"img/favorite.png":"img/favorite_hover.png",null!=a&&(a.src=c),null!=b&&(b.src=c)):(ErrorMessage("Get "+c+" element failed!"),XMLHttpRequestStop(),
XMLHttpRequestStart(GetGuidRemoteArgument()))}else if(""!=GetResponseItem("TVPlayerState"))alert("TVPlayerState != null"),b=document.getElementById("CheckboxTVPlayerMuteRC"),b.value=GetResponseItem("Mute"),b.disabled=!1,b=document.getElementById("CheckboxTVPlayerPauseRC"),b.value=GetResponseItem("Playback"),b.disabled=!1,b=document.getElementById("ButtonTVPlayerDecreaseVolumeRC"),b.disabled=!1,b=document.getElementById("sl_slider"),b.disabled=!1,b=document.getElementById("ButtonTVPlayerIncreaseVolumeRC"),
b.disabled=!1,b=document.getElementById("ButtonPrevTVChannelRC"),b.disabled=!1,b=document.getElementById("ButtonNextTVChannelRC"),b.disabled=!1,b=document.getElementById("ButtonReloadTVChannelRC"),b.disabled=!1,a=GetResponseItem("Volume"),document.getElementById("info").innerText=a,mysl1.setValue(a),g_TVChannelIDRC=GetResponseItem("TVChannelID"),XMLHttpRequestStop(),XMLHttpRequestStart(GetGuidRemoteArgument());else{a=GetResponseItem("TVPlayerVolume");""!=a&&TVPlayerSetVolume2(a);a=GetResponseItem("TVPlayer");
if(""!=a)if("reload"==a)ReloadTVChannel();else if("mute"==a)TVPlayerMute();else if("pause"==a)TVPlayerPause();else if("Increase"==a)TVPlayerSetVolume("increase");else if("Decrease"==a)TVPlayerSetVolume("decrease");else if("GetState"==a)SetTVPlayerStateToRC();else{ErrorMessage("Unknown TVPlayerMode = "+a);return}if(""!=GetResponseItem("ListenRTMPSuck")){a=document.getElementById("TVChannelFile");if(null==a){ErrorMessage("element TVChannelFile == null");return}a.value=GetResponseItem("RTMPSuckFile");
a=document.getElementById("TVChannelStreamer");if(null==a){ErrorMessage("element TVChannelStreamer == null");return}a.value=GetResponseItem("RTMPSuckStreamer")}if(a=GetResponseItem("streamer")){b=document.getElementById("TVchannel");if(null==b){ErrorMessage("element TVchannel == null");return}b=GetResponseItem("ID");c=GetResponseItem("Name");ChangeTYChannelName(b,c,GetResponseItem("logo"),GetResponseItem("country"),"",GetResponseItem("language"),GetResponseItem("description"));var f=GetResponseItem("file");
ChangeTVChannel(f,a,b);_gaq.push(["_trackEvent","Online TV","Play",b+" "+c])}a=GetResponseItem("description2");if(""!=a)c=GetResponseItem("ID"),""==c?ErrorMessage('descriptionID == ""'):(b="",IsOpenFavorites()&&(b="F"),b=document.getElementById(b+"description"+c),null==b?ErrorMessage("elementDescription == null"):b.innerHTML="<p>"+Encoder.htmlDecode(a)+"</p>");else if(a=GetResponseItem("editTVChannel"),""!=a)b=document.getElementById("TVchannelDescription"),null==b?alert("ERROR: element TVchannelDescription == null"):
b.innerHTML=Encoder.htmlDecode(a),a=document.getElementById("TVChannelImgLogo"),null==a?alert("ERROR: elementTVChannelImgLogo == null"):(a=/(.+\/icons\/)(.+)/g.exec(a.src),b=document.getElementById("TVChannelLogo"),null==b?alert("ERROR: elementTVChannelLogo == null"):(null!=a&&(b.value=a[2]),b=document.getElementById("TVChannelLogoFolder"),null==b?alert("ERROR: elementTVChannelLogoFolder == null"):b.innerText=null!=a?a[1]:location.protocol+"//"+location.host+location.pathname+"icons/"));else if(a=
GetResponseItem("editTVChannelApply"),""!=a)"Ok"==a?location.reload():alert(a);else{if(""!=GetResponseItem("editTVChannelCities")){a=document.getElementById("TVChannelSelectCity");if(null==a){ErrorMessage("element TVChannelSelectCity == null");return}for(i=a.options.length-1;0<i;i--)a.remove(i);b=response.getElementsByTagName("editTVChannelCities");if("undefined"!=typeof b)for(b=b[0].getElementsByTagName("City"),i=0;i<b.length;i++)c=b[i],f=document.createElement("OPTION"),a.options.add(f),f.innerText=
GetElementText(c,"Name"),f.value=GetElementText(c,"Value")}AddTVChannelsResponse()||(a=GetResponseItem("changeTVChannel"),""!=a?null==g_reqRemote?ErrorMessage("processStatus200(req1) failed! g_reqRemote == null"):(b="",IsOpenFavorites()&&(b="F"),a=document.getElementById(b+"RadioR"+a),null==a?ErrorMessage("element RadioR == null"):(TableBackground(a,"clicked_Row"),RestoreRCButtons())):(""==g_cancelRemote&&(g_cancelRemote=GetResponseItem("cancelRemote")),""!=g_cancelRemote?(g_cancelRemote="",AbortRemoteControl(),
XMLHttpRequestStop()):(a=GetResponseItem("error"),""!=a?(alert(a),XMLHttpRequestStop()):(a=GetResponseItem("updateGUID"),""!=a?(guid=g_guid=a,b=document.getElementById("InitID"),null==b?alert("ERROR: elementInitID == null"):(c=GetResponseItem("InitID"),""==c?alert('ERROR: initID == ""'):(b.innerHTML=c,Initialization("start",a),XMLHttpRequestStop(),XMLHttpRequestStart(GetGuidRemoteArgument())))):(a=GetResponseItem("socket"),""!=a?"close"==a?(ErrorMessage("processStatus200(req1) failed! socket: "+a),
setTimeout(restartReq,5E3)):ErrorMessage("processStatus200(req1) failed! socket2: "+a):(a=GetResponseItem("ConnectToRemoteControlDispatcherError"),""!=a?(ErrorMessage(a),setTimeout(restartReq,5E3)):(""!=GetResponseItem("guidRemote")&&"block"==document.getElementById("var").style.display&&displ("var",guid),AddRemoteColumn(),null!=req&&4==req.readyState&&(XMLHttpRequestStop(),XMLHttpRequestStart(GetGuidRemoteArgument())))))))))}}}
function GetBandwidthCookie(){var a=get_cookie("Bandwidth");return"true"!=a&&null!=a?!1:!0}
function AddTVChannelsResponseBase(a,c,b,f,l){var e=response.getElementsByTagName(a);if(null==e)return ErrorMessage("AddTVChannelsResponseBase(); elementAddTVChannels == null"),0;if(0==e.length)return 0;if(1!=e.length)return ErrorMessage("AddTVChannelsResponseBase(); elementAddTVChannels.length != 1"),1;a=document.getElementById(c);c="";var k=e[0].getElementsByTagName("NextTVChannelID");if(null!=k&&(1==k.length&&(c=k[0].firstChild.data),a)){k=a.rows[a.rows.length-g_TVChannelsTableRowsLength];if("undefined"!=
typeof k){if("rowAdvertisement"!=k.id)return ErrorMessage('AddTVChannelsResponse(). rowAdvertisement.id != "rowAdvertisement"'),1;""!=c&&isChrome||(k.cells[0].firstChild.style.display="block")}isChrome||g_TVChannelsTableRowsLength--}var k=GetBandwidthCookie(),g=document.getElementById("TVChannelsAreaRCBC1");if(null!=g&&""!=g.innerHTML){if(g=document.getElementById("Advertisement1"))g.style.display="block";g=document.getElementById("TVChannelsAreaRCBC2")}if(null!=g&&""!=g.innerHTML){if(g=document.getElementById("Advertisement2"))g.style.display=
"block";g=document.getElementById("TVChannelsAreaRCBC3")}if(null!=g&&""!=g.innerHTML){if(g=document.getElementById("Advertisement3"))g.style.display="block";g=document.getElementById("TVChannelsAreaRCBC4")}e=e[0].getElementsByTagName("TVChannel");for(i=0;i<e.length;i++){var h=e[i],m=GetElementText(h,"File",!0),y=GetElementText(h,"Streamer",!0),D=GetElementText(h,"Status"),r=h.getElementsByTagName("Logo");if(0!=r.length)var B="icons/"+GetElementText(h,"Logo");var p=GetElementText(h,"ID"),v=GetElementText(h,
"TVPlayerImage"),C=GetElementText(h,"Name"),s=GetElementText(h,"Speed"),w=GetElementText(h,"Country"),x=GetElementText(h,"Category"),q=GetElementText(h,"Language"),t=GetElementText(h,"Checked",!0),E=GetElementText(h,"Deleted"),t=GetElementText(h,"TVPlayerStatus"),z="",A="";"red"==t&&(z='<FONT style="BACKGROUND-COLOR: red">',A="</FONT>");var n=null;if(a){var d=0,d=1;isChrome&&(d=0);d=0<=g_TVChannelsTableRowsLength?a.rows.length-g_TVChannelsTableRowsLength-d:-1;n=a.insertRow(d)}d=null;""!=g_guidRemote&&
k&&(null==g?d=n.insertCell(-1):(d=document.createElement("span"),d.id="TVChannel",d.className="TVChannelRow",d.style.display="block",d.style.borderTop="2px solid #999999"));if(null==n&&null==d)return ErrorMessage("(row == null) && (cell = null)"),1;var u=!1,F=GetElementText(h,"TVPlayerID");2!=D||""==y||"disable"==t||""==m&&3!=F||(u=!0);m=!1;"true"==GetElementText(h,"TVFavorite")&&(m=!0);g_OpenTVPlayer&&(h=d?d:n.insertCell(-1),u&&(t="",g_TVChannelID==p&&(t="checked "),h.innerHTML=h.innerHTML+z+'<INPUT id="'+
b+"Radio"+p+'" value="'+p+'" type="radio" '+t+'name="RadioGroup'+b+'" language="javascript" onclick="getTVChannel(\''+p+"')\">"+A));""!=g_guidRemote&&(h=d?d:n.insertCell(-1),u&&(u="",g_TVChannelIDRC==p&&(u="checked "),h.innerHTML=h.innerHTML+z+'<INPUT id="'+b+"RadioR"+p+'" value="'+C+'" type="radio" '+u+'name="RadioGroupR'+b+'" language="javascript" onclick="Radio_onclick(\''+p+"', GetGuidRemote(), event)\">"+A,d&&(d.onclick=function(a){a||(a=window.event);a=a.target||a.srcElement;"SPAN"==a.tagName&&
(a=a.firstChild,"INPUT"==a.tagName?a.click():ErrorMessage("Invalid TVChannel input"))})));0==r.length||""!=g_guidRemote&&k||(r=d?d:n.insertCell(-1),""!=B&&(r.innerHTML=r.innerHTML+'<img src="'+B+'" style="width:40; height:40" border="0"/>'));r=d?d:n.insertCell(-1);r.innerHTML=r.innerHTML+v+'<FONT style="COLOR: blue; CURSOR: hand; TEXT-DECORATION: '+("true"==E?"line-through":"underline")+';" language="javascript" onclick="getDescription('+p+')">'+C+'</FONT><span id="'+b+"description"+p+'"></span>';
d?(d.innerHTML+=". ",v=d):v=n.insertCell(-1);v.innerHTML+=w;d?(d.innerHTML+=". ",w=d):w=n.insertCell(-1);w.innerHTML+=x;d?(d.innerHTML+=". ",x=d):x=n.insertCell(-1);x.innerHTML+=q;d?("0"!=s&&(d.innerHTML+=". "),q=d):q=n.insertCell(-1);"0"!=s&&(q.innerHTML+=s,d&&(q.innerHTML+=" kbps"));d?(d.innerHTML+=". ",s=d):s=n.insertCell(-1);q="img/favorite_hover.png";m&&(q="img/favorite.png");s.innerHTML=s.innerHTML+'<img src="'+q+'" id="F'+b+p+'" onclick="favoriteClick('+p+')"/>';d&&null!=g&&g.appendChild(d)}null==
f?alert("reqAddTVChannels == null"):(f.abort(),f=null);!0==g_stopAddingTVchannels||"undefined"!=typeof c&&""!=c?(b=document.getElementById("WaitID"),null!=b&&(b.innerHTML=c+" "),!0==g_stopAddingTVchannels&&(g_stopAddingTVchannels=!1,RemoveOldTVChannels(document.getElementById("ChannelsTable")),c=""),g_callbackAddTVChannels=l,g_nexTVChannelID=c,setTimeout("g_callbackAddTVChannels(g_country, g_city, g_category, g_language, g_player, g_nexTVChannelID)",0)):(WaitTVChannels(!1),b=document.getElementById("WaitID"),
null!=b&&(b.innerHTML=""));return 1}
function TableBackground(a,c){for(;!a.tagName||"TR"!=a.tagName;){a=a.parentNode;if(null==a){ErrorMessage("TableBackground(row, className). row == null");return}if("TVChannel"==a.id&&"SPAN"==a.tagName){a.className=c;null!=g_clicked_TVchannel&&(g_clicked_TVchannel.className="");g_clicked_TVchannel=a;return}}for(var b=/\bhover_Row\b/,f=a;!f.tagName||"TABLE"!=f.tagName;)f=f.parentNode;var l=/\bclicked_Row\b/;a.getAttribute("clicked_Row")||(a.className=a.className.replace(b,""),a.className+=" clicked_Row",
a.setAttribute("clicked_Row",!0),b=f.getAttribute("last_Clicked_Row"),null!==b&&""!==b&&a.sectionRowIndex!=b&&(b=f.tBodies[0].rows[b],b.className=b.className.replace(l,""),b.removeAttribute("clicked_Row")),f.setAttribute("last_Clicked_Row",a.sectionRowIndex))}
function highlight_Table_Rows(a,c,b,f){a=document.getElementById(a);if(null!=a){"undefined"==typeof f&&(f=!0);if(c){var l=RegExp("\\b"+c+"\\b");a.onmouseover=a.onmouseout=function(a){a||(a=window.event);for(var b=a.target||a.srcElement;!b.tagName||!b.tagName.match(/td|th|table/i);)b=b.parentNode;"TR"==b.parentNode.tagName&&"TBODY"==b.parentNode.parentNode.tagName&&(b=b.parentNode,b.getAttribute("clicked_Row")||(b.className="mouseover"==a.type?b.className+" "+c:b.className.replace(l," ")))}}b&&(a.onclick=
function(a){a||(a=window.event);for(a=a.target||a.srcElement;!a.tagName||!a.tagName.match(/td|th|table/i);)if("P"==a.tagName||"SPAN"==a.tagName)a=a.parentNode;else return;"TR"==a.parentNode.tagName&&"TBODY"==a.parentNode.parentNode.tagName&&(a=a.parentNode,""==a.id&&(a=a.cells[0].firstChild)&&("INPUT"!=a.tagName?ErrorMessage("highlight_Table_Rows(...). input.tagName: "+a.tagName+' != "INPUT"'):a.click()))})}}
function AddTVChannelsResponse(){if(IsOpenFavorites())return AddTVChannelsResponseBase("AddTVChannels","ChannelsTable","F",g_reqAddTVChannels,AddFavoriteTVChannels);var a=response.getElementsByTagName("AddTVCities");if(null!=a){var c=document.getElementById("SelectCity");if(null==c)return ErrorMessage("elementSelectCity == null"),0;if(null!=a[0])for(a=a[0].getElementsByTagName("TVCity"),i=0;i<a.length;i++){var b=a[i],f=document.createElement("OPTION");c.options.add(f);f.text=GetElementText(b,"CityName",
!0);f.value=GetElementText(b,"CityID",!0);"Yes"==GetElementText(b,"CitySelected",!0)&&(f.selected=!0)}}return AddTVChannelsResponseBase("AddTVChannels","ChannelsTable","",g_reqAddTVChannels,AddTVChannels)}function IsOpenFavorites(){var a=document.getElementById("CheckboxFavorites");if(null==a)alert("ERROR: elementCheckboxFavorites == null");else return null==a.src.match(/favorite_hover.png/)?!0:!1}
function favoritesClick(){null==document.getElementById("CheckboxFavorites")?alert("ERROR: elementCheckboxFavorites == null"):(ToogleFavorites(!IsOpenFavorites()),SelectTVChannels())}function IsFavorites(){return"true"!=get_cookie("Favorites")?!1:!0}
function ToogleFavorites(a){var c=document.getElementById("CheckboxFavorites");if(null==c)alert("ERROR: elementCheckboxFavorites == null");else{var b=document.getElementById("TVPChannelsSelect");if(null==b)alert("ERROR: elementTVChannelsSelect == null");else{var f=document.getElementById("TVPChannelsHelp");if(null==f)alert("ERROR: elementTVChannelsHelp == null");else{var l=document.getElementById("TVFavoritesHelp");if(null==l)alert("ERROR: elementTVFavoritesHelp == null");else{var e=document.getElementById("TVFavoritesTitle");
if(null==e)alert("ERROR: elementTVFavoritesTitle == null");else{var k=document.getElementById("AddFavoritesHelp");if(null==k)alert("ERROR: elementAddFavoritesHelp == null");else{var g="",h="",m="";a?(g="none",h="block",c.src="img/favorite.png",c.value=1,m="true"):(c.src="img/favorite_hover.png",c.value=0,g="block",h="none",m="false");b.style.display=g;f.style.display=g;l.style.display=h;e.style.display=h;k.style.display=h;SetCookie("Favorites",m)}}}}}}}
function favoriteClick(a){var c=g_guid;""!=g_guidRemote&&(c=g_guidRemote);""==c?ErrorMessage("favoriteClick(e) failed! guid == ''"):(null==g_reqFavorite&&(g_reqFavorite=loadXMLDoc1()),null==g_reqFavorite&&ErrorMessage("favoriteClick(e) failed! g_reqFavorite == null"),g_reqFavorite.onreadystatechange=processReqFavorite,g_reqFavorite.open("GET","XMLHttpRequest.srf?FavoriteID="+a+"&guidFavorite="+c,!0),g_reqFavorite.send(null))}function processReqFavorite(){processReqChange1(g_reqFavorite)}
function SelectTVChannels(){var a=document.getElementById("SelectCountry");if(null==a)alert("ERROR: elementSelectCountry == null");else{var a=a.options[a.selectedIndex],c=document.getElementById("SelectCity");if(null==c)alert("ERROR: elementSelectCity == null");else{c=c.options[c.selectedIndex];""!=g_country&&g_country!=a.value&&(c.value="All cities");var b=document.getElementById("SelectCategory");if(null==b)alert("ERROR: elementSelectCategory == null");else{var b=b.options[b.selectedIndex],f=document.getElementById("SelectLanguage");
if(null==f)alert("ERROR: elementSelectLanguage == null");else{var f=f.options[f.selectedIndex],l=document.getElementById("SelectPlayer");null==l?alert("ERROR: elementSelecttPlayer == null"):(l=l.options[l.selectedIndex],IsWaitTVChannels()?(g_country=a.value,g_city=c.value,g_category=b.value,g_language=f.value,g_player=l.value,g_stopAddingTVchannels=!0):IsOpenFavorites()?AddFavoriteTVChannels():AddTVChannels(a.value,c.value,b.value,f.value,l.value))}}}}}
function AddFavoriteTVChannels(a,c,b,f,l,e){c=document.getElementById("ChannelsTable");null==document.getElementById("SelectCity")?alert("ERROR: elementSelectCity == null"):(a="","undefined"!=typeof e?a="&NexTVChannelID="+e:(WaitTVChannels(!0),RemoveOldTVChannels(c)),null==g_reqAddTVChannels&&(g_reqAddTVChannels=loadXMLDoc1()),null==g_reqAddTVChannels&&ErrorMessage("g_reqAddTVChannels == null"),g_reqAddTVChannels.onreadystatechange=processReqAddTVChannels,e=!1,""!=g_guidRemote&&GetBandwidthCookie()&&
(e=!0),c="",c=""==g_guidRemote?g_guid:g_guidRemote,g_reqAddTVChannels.open("GET","XMLHttpRequest.srf?addFavoriteTVChannels="+c+a+"&RCBandwidth="+e,!0),g_reqAddTVChannels.send(null))}
function RemoveOldTVChannels(a){if(a){var c=a.rows[0],b=1;"undefined"==typeof c||"row_header"!=c.id&&"row_headerF"!=c.id||(b=0);for(i=a.rows.length-1;i>0-b;i--)c=a.rows[i],"rowAdvertisement"==c.id?c.cells[0].firstChild.style.display="none":a.deleteRow(i);g_TVChannelsTableRowsLength=a.rows.length-1+b}a=document.getElementById("TVChannelsAreaRCBC1");null!=a&&(a.innerHTML="");a=document.getElementById("TVChannelsAreaRCBC2");null!=a&&(a.innerHTML="");a=document.getElementById("TVChannelsAreaRCBC3");null!=
a&&(a.innerHTML="");a=document.getElementById("TVChannelsAreaRCBC4");null!=a&&(a.innerHTML="");a=document.getElementById("Advertisement1");null!=a&&(a.style.display="none");a=document.getElementById("Advertisement2");null!=a&&(a.style.display="none");a=document.getElementById("Advertisement3");null!=a&&(a.style.display="none")}function RemoveOldCities(){var a=document.getElementById("SelectCity");if(null==a)alert("ERROR: elementSelectCity == null");else for(i=a.length-1;0<i;i--)a.remove(i)}
function AddTVChannels(a,c,b,f,l,e){g_country=a;g_city=c;g_category=b;g_language=f;g_player=l;var k=document.getElementById("FindTVChannels");if(null==k)alert("ERROR: elementFindTVChannels == null");else{var k=k.value,g=!1;if(""!=k){if(g_FindTVChannels==k&&"undefined"==typeof e)return;g=!0}g_FindTVChannels=k;var h=document.getElementById("ChannelsTable"),m=document.getElementById("SelectCity");if(null==m)alert("ERROR: elementSelectCity == null");else{null==g_reqAddTVChannels&&(g_reqAddTVChannels=
loadXMLDoc1());null==g_reqAddTVChannels&&ErrorMessage("Radio_onclick(...) failed! g_reqAddTVChannels == null");g_reqAddTVChannels.onreadystatechange=processReqAddTVChannels;var y="";"undefined"!=typeof e?y="&NexTVChannelID="+e:(WaitTVChannels(!0),RemoveOldTVChannels(h));e=document.getElementById("SelectCountry");null==e?alert("ERROR: elementSelectCountry == null"):(e.disabled=g,m.disabled=g,e=document.getElementById("SelectCategory"),null==e?alert("ERROR: elementSelectCategory == null"):(e.disabled=
g,e=document.getElementById("SelectLanguage"),null==e?alert("ERROR: elementSelectLanguage == null"):(e.disabled=g,e=document.getElementById("SelectPlayer"),null==e?alert("ERROR: elementSelectPlayer == null"):(e.disabled=g,e=document.getElementById("CheckboxRC"),null!=e&&(e.disabled=g),g=1,""==g_guidRemote&&(null==e?"false"==get_cookie("RC")&&(g=0):(m="false",!0==e.checked?(m="true",g=1):g=0,SetCookie("RC",m))),e=!1,""!=g_guidRemote&&GetBandwidthCookie()&&(e=!0),m="",m=""==g_guidRemote?g_guid:g_guidRemote,
g_reqAddTVChannels.open("GET","XMLHttpRequest.srf?addTVChannels="+m+"&Country="+a+"&City="+c+"&Category="+b+"&Language="+f+"&Player="+l+y+"&RemoteControl="+g+"&FindTVChannels="+k+"&RCBandwidth="+e,!0),g_reqAddTVChannels.send(null)))))}}}function processReqAddTVChannels(){processReqChange1(g_reqAddTVChannels)}function WaitTVChannels(a){g_wait=a;a=document.getElementById("wait");null!=a&&(a.style.display=!0==g_wait?"block":"none")}function GetGuidRemote(){return g_guidRemote}
function getDescription(a){var c="";IsFavorites()&&(c="F");c=document.getElementById(c+"description"+a);null==c?ErrorMessage("getDescription() failed! elementDescription == null"):""!=c.innerHTML?c.style.display="none"==c.style.display?"block":"none":(null==g_reqGetDescription&&(g_reqGetDescription=loadXMLDoc1()),null==g_reqGetDescription&&ErrorMessage("getDescription("+a+") failed! g_reqGetDescription == null"),g_reqGetDescription.onreadystatechange=processReqGetDescription,g_reqGetDescription.open("GET",
"XMLHttpRequest.srf?GetDescription="+a,!0),g_reqGetDescription.send(null))}function processReqGetDescription(){processReqChange1(g_reqGetDescription)}
function EditTVChannel(a){"undefined"==typeof g_reqEditTVChannel?alert("Currently editing of TV channel is not available in the remote control mode"):null==guid?ErrorMessage("Open TV player first."):(null==g_reqEditTVChannel&&(g_reqEditTVChannel=loadXMLDoc1()),null==g_reqEditTVChannel&&ErrorMessage("EditTVChannel("+a+") failed! g_reqEditTVChannel == null"),g_reqEditTVChannel.onreadystatechange=processReqEditTVChannel,g_reqEditTVChannel.open("GET","XMLHttpRequest.srf?EditTVChannel="+a+"&guidEditTVChannel="+
guid,!0),g_reqEditTVChannel.send(null))}function processReqEditTVChannel(){processReqChange1(g_reqEditTVChannel)}
function NewTVchannel(){"undefined"==typeof g_reqNewTVChannel?alert("Currently New TV channel is not available in the remote control mode"):(null==g_reqNewTVChannel&&(g_reqNewTVChannel=loadXMLDoc1()),null==g_reqNewTVChannel&&ErrorMessage("NewTVChannel() failed! g_reqNewTVChannel == null"),g_reqNewTVChannel.onreadystatechange=processReqNewTVChannel,g_reqNewTVChannel.open("GET","XMLHttpRequest.srf?NewTVChannel=1",!0),g_reqNewTVChannel.send(null))}
function processReqNewTVChannel(){processReqChange1(g_reqNewTVChannel)}function ErrorMessage(a){a=a.replace("<","&lt;");a=a.replace(">","&gt;");MessageElement('<FONT color="red">ERROR: '+a+"</FONT>")}function AbortRemoteControl(){CancelRemoteControl1();var a=document.getElementById("var");return null==a?!0:"block"==a.style.display?(displ("var"),!0):!1}
function CancelRemoteControl1(){var a=document.getElementById("DivCancelRemoteControl");if(null!=a)if("block"==a.style.display&&displRemoteControl(),a=document.getElementById("ChannelsTable"),null==a)alert("ERROR: ChannelsTable == null");else{for(i=0;i<a.rows.length;i++){var c;c=a.rows[i].cells[1];if(0==i&&"R"!=c.id)return;c.style.display="none"}a=document.getElementById("DivGUIDRemote");null==a?ErrorMessage("CancelRemoteControl() failed! DivGUIDRemote == null"):a.innerHTML=""}}
function AddFavorites(){var a=document.getElementById("inputAddFavorites").value;""==a?alert("Source bowser's ID is empty."):(null==g_reqAddFavorites&&(g_reqAddFavorites=loadXMLDoc1()),null==g_reqAddFavorites&&ErrorMessage("NewTVChannel() failed! g_reqAddFavorites == null"),g_reqAddFavorites.onreadystatechange=processAddFavorites,g_reqAddFavorites.open("GET","XMLHttpRequest.srf?AddFavorites="+a+"&guidFavoritesTo="+guid,!0),g_reqAddFavorites.send(null))}
function processAddFavorites(){processReqChange1(g_reqAddFavorites)}function AddFavoritesDisplay(){var a=document.getElementById("AddFavoritesArea");null==a?ErrorMessage("AddFavoritesDisplay() failed! elementAddFavoritesArea == null"):"none"==a.style.display?(a.style.display="block",document.getElementById("inputAddFavorites").focus()):a.style.display="none"};