var g_autostart=!0,g_primary="html5",g_width=480,g_height=270,g_guidRemote="",g_reqRemoteControlInitialization=null,g_reqUpdateGUID=null,g_reqGetTVChannel=null,g_reqEditTVChannel=null,g_reqEditTVChannelApply=null,g_reqListenRTMPSuck=null,g_reqTVChannelSelectCountry=null,g_reqNewTVChannel=null,g_reqTVPlayerError=null,g_reqTVPlayerStateToRC=null,g_reqRemoteTVPlayerGetState=null,g_reqRemoteTVPlayer=null,g_TVPlayerType=2,g_FlashDetected=!1,g_VLCDetected=!1,g_FullScreen=!1;
function IsErrorMessage(a,b){return null==a?(ErrorMessage(b),null):1}function resetDefaults(){g_autostart=!0;g_primary="html5";g_width=480;g_height=270}
function SetupJwPlayer(){var a=jwplayer("mediaspace1");a?a.setup({provider:"rtmp",autostart:!0,fullscreen:!0,width:g_width,height:g_height,logo:{file:"http://p.jwpcdn.com/6/0/logo.png",link:"http://www.longtailvideo.com/jwpabout/?a=l&v=6.0.2813&m=f&e=a"},abouttext:"JW Player 6.0.2813",aboutlink:"http://www.longtailvideo.com/jwpabout/?a=r&v=6.0.2813&m=f&e=a",primary:"flash",events:{onError:function(a){},onReady:function(){SetTVPlayerStateToRC();TVPlayerVolume()},onMute:function(a){SetTVPlayerStateToRC();
SetTVPlayerMuteCheckbox()},onPlay:function(a){SetTVPlayerStateToRC();SetTVPlayerMuteCheckbox();SetTVPlayerPauseCheckbox()},onPause:function(a){SetTVPlayerStateToRC();SetTVPlayerPauseCheckbox()},onVolume:function(a){SetTVPlayerStateToRC();TVPlayerVolume()}}}):alert("ERROR: SetupJwPlayer(). mediaspace == null")}function TVchannelDescriptionResize(){document.getElementById("TVchannelDescription").style.height=parseInt(g_height)+20}
function IsPlayerInstalled(){var a=get_cookie("TVPlayerHeight");null!=a&&(g_height=a);a=get_cookie("TVPlayerWidth");null!=a?g_width=a:(a=window.screen.width-20,g_width>a&&(g_width=a,g_height=9*g_width/16));TVchannelDescriptionResize();ReloadTVChannel();CheckTVPlayerAspectRatio()}
function setupPlayer2(a,b){MessageElement("");if(""==b)ErrorMessage('setupPlayer. streamer == ""');else if(""==a)(vlc=getVLC("vlc"))?doGo(b):ErrorMessage('setupPlayer. file == "". Open VLC first.');else{var c=jwplayer("mediaspace1");c&&c.setup({file:a,provider:"rtmp",streamer:b,autostart:!0,fullscreen:!0,width:g_width,height:g_height,logo:{file:"http://p.jwpcdn.com/6/0/logo.png",link:"http://www.longtailvideo.com/jwpabout/?a=l&v=6.0.2813&m=f&e=a"},abouttext:"JW Player 6.0.2813",aboutlink:"http://www.longtailvideo.com/jwpabout/?a=r&v=6.0.2813&m=f&e=a",
events:{onError:function(a){null==g_reqTVPlayerError&&(g_reqTVPlayerError=loadXMLDoc1());null==g_reqTVPlayerError&&ErrorMessage("CheckboxListenRTMPSuck_onclick() failed! g_reqTVPlayerError == null");g_reqTVPlayerError.onreadystatechange=processReqTVPlayerError;g_reqTVPlayerError.open("GET","XMLHttpRequest.srf?TVPlayerError="+a.message+"&guidTVPlayerError="+guid,!0);g_reqTVPlayerError.send(null)},onReady:function(){}}})}}function processReqTVPlayerError(){processReqChange1(g_reqTVPlayerError)}
function ChangeTYChannelName(a,b,c,d,e,g,f){a=document.getElementById("TVchannel");null==a?alert("ERROR: element TVchannel == null"):a.innerHTML=b+". "+d+". "+g;b=document.getElementById("TVchannelDescription");null==b?alert("ERROR: element TVchannelDescription == null"):b.innerHTML='<img style="MARGIN-RIGHT: 5px; float:left" src="'+c+'" border="0"/><p>'+Encoder.htmlDecode(f)+"</p>"}function restartReq(){MessageElement("");XMLHttpRequestStop();XMLHttpRequestStart(GetGuidRemoteArgument())}
function RemoteControlInitialization(a){""==a?ErrorMessage("RemoteControlInitialization("+a+") failed!"):(displ("var",a),MessageElement(""))}
function Initialization(a,b){null==g_reqRemote&&(g_reqRemoteControlInitialization=loadXMLDoc1());null==g_reqRemoteControlInitialization?ErrorMessage("g_reqRemoteControlInitialization == null"):"undefined"==typeof b||null==b||""==b?ErrorMessage("Initialization("+a+", "+b+") failed!"):(g_reqRemoteControlInitialization.onreadystatechange=processReqRCInitState,g_reqRemoteControlInitialization.open("GET","XMLHttpRequest.srf?remoteControlInitialization="+a+"&remoteControlInitializationGUID="+b,!0),g_reqRemoteControlInitialization.send(null))}
function displ(a,b){var c=document.getElementById("BtnRemoteControlInitialization"),d=document.getElementById("HideStatus"),e=document.getElementById(a);"none"==document.getElementById(a).style.display?(e.style.display="block",c.style.display="none",d.value="block",c="start"):(e.style.display="none",c.style.display="block",d.value="none",c="stop");"undefined"!=typeof b&&Initialization(c,b)}function processReqRCInitState(){processReqChange1(g_reqRemoteControlInitialization)}
function displRemoteControl(){var a=document.getElementById("DivRemoteControlInitialization"),b=document.getElementById("DivCancelRemoteControl");"none"==a.style.display?(a.style.display="block",b.style.display="none"):(a.style.display="none",b.style.display="block")}
function CancelRemoteControl(){"undefined"!=typeof guid&&null!=guid&&""!=guid&&(g_cancelRemote="CancelRemoteControl()",null==g_reqRemote&&(g_reqRemote=loadXMLDoc1()),null==g_reqRemote&&ErrorMessage("CancelRemoteControl() failed! g_reqRemote == null"),g_reqRemote.onreadystatechange=processReqChangeRemote,g_reqRemote.open("GET","XMLHttpRequest.srf?&cancelRemote="+guid,!0),g_reqRemote.send(null),guid="")}
function PluginDetector(a,b,c,d,e){var g=document.getElementById("PlayerError");g.style.display="none";var f=PluginDetect;if("undefined"==typeof f)return alert("ERROR: PluginDetect undefined"),!1;if(!f.getVersion)return alert("ERROR: $.getVersion == null"),!1;var h=f.getVersion(a);if(!f.isMinVersion)return alert("ERROR: $.isMinVersion == null"),!1;a=f.isMinVersion(a,b);b="";switch(a){case 1:break;case 0:b=FormatString(g_strUnknownPluginVersion,[h,c]);f.isIE&&(b+=d);break;case -0.1:b=FormatString(g_strOldPlugin,
[c,h]);break;case -0.2:b=FormatString(g_strPluginNotEnabled,Array(c));break;case -1:b=FormatString(g_strPluginNotInstalled,Array(c));break;case -3:b=g_strBadInput;break;default:b=FormatString(g_strUnknownStatus,[a,c])}""!=b&&(g.style.display="block",g.innerHTML=FormatString(g_strPluginError,[b,e,c]));return!0}
function CreateVLC(a){var b=null;if(b=getVLC("vlc"))return doGo(a),b;var c=document.getElementById("VLCPlayer");if(!g_VLCDetected){if(!PluginDetector("VLC","1,0,0,0","VLC Media",g_strVLC2_0_7Error,"http://www.videolan.org/"))return b;g_VLCDetected=!0}-1==navigator.appName.indexOf("Microsoft Internet")?(c.innerHTML='\t<EMBED pluginspage="" type="application/x-vlc-plugin" progid="VideoLAN.VLCPlugin.2" width="'+g_width+'" height="'+g_height+'" id="vlc" target="'+a+'" autoplay="true" autoloop="true">\t</EMBED>',
b=getVLC("vlc")):(c.innerHTML='<OBJECT classid="clsid:9BE31822-FDAD-461B-AD51-BE1D1C159921" codebase="http://www.videolan.org/" id="vlc" events="True" VIEWASTEXT>\t<param name="MRL" value="" />\t<param name="ShowDisplay" value="True" />\t<param name="AutoPlay" value="true" /></OBJECT>',b=getVLC("vlc"),doGo(a),b.style.width=g_width,b.style.height=g_height);RestoreVolume();monitor();return b}
function ChangeTVChannel(a,b,c){if(!1!=g_OpenTVPlayer){var d=getVLC("vlc");document.getElementById("JwPlayer");d=document.getElementById("JwPlayer");if(""!=a){doStop();if(!g_FlashDetected){if(!PluginDetector("Flash","1,0,0,0","Adobe Flash","","http://get.adobe.com/flashplayer/"))return;g_FlashDetected=!0}var e=null;try{e=jwplayer("mediaspace1")}catch(g){alert("ERROR: function ChangeTVChannel(...). jwplayer('mediaspace1') failed!");return}if(null==e||!1==e.getFullscreen())d.innerHTML='\t\t\t\t<div id="mediaspace1" style="width:'+
g_width+"; height:"+g_height+'; overflow:auto; padding:0px; border: 1px solid #999999">\t\t\t\t\tAdobe Flash Player is missing.<a href="http://get.adobe.com/flashplayer/">Click to install</a>.\t\t\t\t\tClose your web browser and open it again, if you see this message after you install Adobe Flash Player.\t\t\t\t</div>',SetupJwPlayer();document.getElementById("VLCPlayer").innerHTML="";if(d=getVLC("vlc")){alert("ERROR: function ChangeTVChannel(...). remove VLC failed!");return}g_FullScreen=!1;e=jwplayer("mediaspace1");
if(!e){alert("ERROR: ChangeTVChannel(). mediaspace == null");return}e.load({file:a,streamer:b});g_TVPlayerType=0}else{a=!1;e=jwplayer("mediaspace1");if("undefined"==typeof e){alert("ERROR: mediaspace is undefined");return}null!=e&&(e.pause(!0),a=e.getFullscreen());!1==a&&(d.innerHTML="");d=CreateVLC(b);if(!d)return;"undefined"!=typeof d.video&&!g_FullScreen&&a&&(g_FullScreen=!0,doFS());g_TVPlayerType=1}SetCookie("TVChannel",c);g_TVChannelID=c;document.getElementById("TVPlayerControl").style.display=
"block";b="Radio"+c;c=document.getElementById(b);null!=c&&(c.checked=!0,TableBackground(c,"clicked_Row"));c=document.getElementById("F"+b);null!=c&&(c.checked=!0,TableBackground(c,"clicked_Row"))}}function OpenTVPlayer(){var a=document.getElementById("CheckboxTVPlayer");null==a?alert("OpenTVPlayer() failed! CheckboxTVPlayer == null"):(SetCookie("OpenTVPlayer",a.checked),location.reload())}function GetGuidRemoteArgument(){return""!=g_guidRemote?"&guidRC="+g_guidRemote:""}
function UpdateGUID(){null==g_reqUpdateGUID&&(g_reqUpdateGUID=loadXMLDoc1());null==g_reqUpdateGUID&&ErrorMessage("UpdateGUID(...) failed! g_reqUpdateGUID == null");g_reqUpdateGUID.onreadystatechange=processReqUpdateGUID;g_reqUpdateGUID.open("GET","XMLHttpRequest.srf?UpdateGUID="+g_guid,!0);g_reqUpdateGUID.send(null)}function processReqUpdateGUID(){getVLC("vlc");document.getElementById("JwPlayer");processReqChange1(g_reqUpdateGUID)}
function getTVChannel(a){null==g_reqGetTVChannel&&(g_reqGetTVChannel=loadXMLDoc1());null==g_reqGetTVChannel&&ErrorMessage("getTVChannel(...) failed! g_reqGetTVChannel == null");g_reqGetTVChannel.onreadystatechange=processReqGetTVChannel;g_reqGetTVChannel.open("GET","XMLHttpRequest.srf?GetTVChannel="+a,!0);g_reqGetTVChannel.send(null)}function processReqGetTVChannel(){processReqChange1(g_reqGetTVChannel)}
function EditTVChannelCancel(){var a=document.getElementById("TVchannelDescription");null==a?alert("ERROR: element TVchannelDescription == null"):a.innerHTML=""}
function EditTVChannelApply(a){var b=document.getElementById("TVChannelName");if(null==b)alert("ERROR: element TVChannelName == null");else{var c=document.getElementById("TVChannelStatus"),d=document.getElementById("TVChannelSelectCountry"),e=document.getElementById("TVChannelSelectCity"),g=document.getElementById("TVChannelSelectCategory"),f=document.getElementById("TVChannelSelectLanguage"),h=document.getElementById("TVChannelPlayers");null==g_reqEditTVChannelApply&&(g_reqEditTVChannelApply=loadXMLDoc1());
null==g_reqEditTVChannelApply&&ErrorMessage("EditTVChannelApply("+a+") failed! g_reqEditTVChannelApply == null");g_reqEditTVChannelApply.onreadystatechange=processReqEditTVChannelApply;g_reqEditTVChannelApply.open("GET","XMLHttpRequest.srf?EditTVChannelApply="+a+"&TVChannelName="+encodeURIComponent(b.value)+"&TVChannelNameRu="+encodeURIComponent(document.getElementById("TVChannelNameRu").value)+"&TVChannelNameInternational="+encodeURIComponent(document.getElementById("TVChannelNameInternational").value)+
"&TVChannelFile="+document.getElementById("TVChannelFile").value+"&TVChannelStreamer="+document.getElementById("TVChannelStreamer").value+"&TVChannelStatus="+c.options[c.selectedIndex].value+"&TVChannelSelectCountry="+d.options[d.selectedIndex].value+"&TVChannelSelectCity="+e.options[e.selectedIndex].value+"&TVChannelSelectCategory="+g.options[g.selectedIndex].value+"&TVChannelSelectLanguage="+f.options[f.selectedIndex].value+"&TVChannelLogo="+document.getElementById("TVChannelLogo").value+"&TVChannelSpeed="+
document.getElementById("TVChannelSpeed").value+"&TVChannelSite="+encodeURIComponent(document.getElementById("TVChannelSite").value)+"&TVChannelProgram="+encodeURIComponent(document.getElementById("TVChannelProgram").value)+"&TVChannelEmail="+encodeURIComponent(document.getElementById("TVChannelEmail").value)+"&TVChannelPage="+encodeURIComponent(document.getElementById("TVChannelPage").value)+"&TVChannelPlayers="+h.options[h.selectedIndex].value+"&TVChannelDescriptionEdit="+encodeURIComponent(document.getElementById("TVChannelDescriptionEdit").value)+
"&TVChannelDescriptionRu="+encodeURIComponent(document.getElementById("TVChannelDescriptionRu").value)+"&TVChannelDescriptionInternational="+encodeURIComponent(document.getElementById("TVChannelDescriptionInternational").value)+"&TVChannelHide="+document.getElementById("TVChannelHide").checked+"&TVChannelPageError="+document.getElementById("TVChannelPageError").value+"&TVChannelPlayerError="+document.getElementById("TVChannelPlayerError").value,!0);g_reqEditTVChannelApply.send(null);SetCookie("FindTVChannels",
b.value)}}function processReqEditTVChannelApply(){processReqChange1(g_reqEditTVChannelApply)}function TVChannelTest(){setupPlayer2(TVChannelFile.value,TVChannelStreamer.value)}
function CheckboxListenRTMPSuck_onclick(){var a=document.getElementById("ListenRTMPSuck");null==a?alert("ERROR: elementListenRTMPSuck == null"):(null==g_reqListenRTMPSuck&&(g_reqListenRTMPSuck=loadXMLDoc1()),null==g_reqListenRTMPSuck&&ErrorMessage("CheckboxListenRTMPSuck_onclick() failed! g_reqListenRTMPSuck == null"),g_reqListenRTMPSuck.onreadystatechange=processReqListenRTMPSuck,g_reqListenRTMPSuck.open("GET","XMLHttpRequest.srf?ListenRTMPSuck="+a.checked+"&guidEditTVChannel="+guid,!0),g_reqListenRTMPSuck.send(null))}
function processReqListenRTMPSuck(){processReqChange1(g_reqListenRTMPSuck)}
function TVChannelSelectCountry(){var a=document.getElementById("TVChannelSelectCountry");null==a?alert("ERROR: elementTVChannelSelectCountry == null"):(a=a.options[a.selectedIndex].value,null==g_reqTVChannelSelectCountry&&(g_reqTVChannelSelectCountry=loadXMLDoc1()),null==g_reqTVChannelSelectCountry&&ErrorMessage("CheckboxListenRTMPSuck_onclick() failed! g_reqTVChannelSelectCountry == null"),g_reqTVChannelSelectCountry.onreadystatechange=processReqTVChannelSelectCountry,g_reqTVChannelSelectCountry.open("GET",
"XMLHttpRequest.srf?TVChannelSelectCountryID="+a),g_reqTVChannelSelectCountry.send(null))}function processReqTVChannelSelectCountry(){processReqChange1(g_reqTVChannelSelectCountry)}function TVChannelSelectCity(){}
function TVChannelLogoTest(){var a=document.getElementById("TVChannelLogo");if(null==a)alert("ERROR: elementTVChannelLogo == null");else{var b=document.getElementById("TVChannelImgLogo");if(null==b)alert("ERROR: elementTVChannelImgLogo == null");else{var c=document.getElementById("TVChannelLogoFolder");null==c?alert("ERROR: elementTVChannelLogoFolder == null"):b.src=c.innerText+a.value}}}
function NewTVchannel(){null==g_reqNewTVChannel&&(g_reqNewTVChannel=loadXMLDoc1());null==g_reqNewTVChannel&&ErrorMessage("NewTVChannel() failed! g_reqNewTVChannel == null");g_reqNewTVChannel.onreadystatechange=processReqNewTVChannel;g_reqNewTVChannel.open("GET","XMLHttpRequest.srf?NewTVChannel=1",!0);g_reqNewTVChannel.send(null)}function processReqNewTVChannel(){processReqChange1(g_reqNewTVChannel)}
function CheckTVPlayerAspectRatio(){var a=document.getElementById("TVPlayerWidth");null!=a&&""==a.value&&(a.value=g_width);var b=document.getElementById("TVPlayerHeight");null!=b&&""==b.value&&(b.value=g_height);var c=document.getElementById("RadioTVPlayerAspectRatio4-3");if(null!=c){c.checked=!1;var d=document.getElementById("RadioTVPlayerAspectRatio16-9");null!=d&&(d.checked=!1,3==4*b.value/a.value?c.checked=!0:9==16*b.value/a.value&&(d.checked=!0))}}
function TVPlayerResize(){if(null==document.getElementById("TVPlayerWidth"))alert("ERROR: elementTVPlayerWidth == null");else if(null==document.getElementById("TVPlayerHeight"))alert("ERROR: elementTVPlayerHeight == null");else{g_width=TVPlayerWidth.value;g_height=TVPlayerHeight.value;switch(g_TVPlayerType){case 0:var a=jwplayer("mediaspace1");if(!a){alert("ERROR: TVPlayerResize(). mediaspace == null");return}a.resize(g_width,g_height);break;case 1:a=getVLC("vlc");if(!a){alert("ERROR: TVPlayerResize(). vlc == null");
return}a.style.width=g_width;a.style.height=g_height;break;default:ErrorMessage("Unknown g_TVPlayerType = "+g_TVPlayerType)}CheckTVPlayerAspectRatio();SetCookie("TVPlayerWidth",g_width);SetCookie("TVPlayerHeight",g_height);TVchannelDescriptionResize()}}
function TVPlayerAspectRatio(a){var b=document.getElementById("TVPlayerWidth");if(null==b)alert("ERROR: elementTVPlayerWidth == null");else{var c=document.getElementById("TVPlayerHeight");null==c?alert("ERROR: elementTVPlayerHeight == null"):("4:3"==a?c.value=3*b.value/4:"16:9"==a?c.value=9*b.value/16:alert("Unknown AspectRatio: "+a),TVPlayerResize())}}
function TVPlayerPause(){switch(g_TVPlayerType){case 0:var a=jwplayer("mediaspace1");if(!a){alert("ERROR: TVPlayerPause(). mediaspace == null");break}var b=!0;"PAUSED"==a.getState()&&(b=!1);a.pause(b);break;case 1:getVLC("vlc").playlist.togglePause();break;case 2:break;default:ErrorMessage("Unknown g_TVPlayerType = "+g_TVPlayerType)}}
function TVPlayerMute(){switch(g_TVPlayerType){case 0:var a=jwplayer("mediaspace1");if(!a){alert("ERROR: TVPlayerMute(). mediaspace == null");break}a.setMute(!jwplayer("mediaspace1").getMute());break;case 1:getVLC("vlc").audio.toggleMute();break;case 2:break;default:ErrorMessage("Unknown g_TVPlayerType = "+g_TVPlayerType)}}
function SetTVPlayerMuteCheckbox(){var a=document.getElementById("CheckboxTVPlayerMute");if(null!=a){var b=jwplayer("mediaspace1");if(b){var c=!1;b.getMute()&&(c=!0);a.checked=c}else alert("ERROR: SetTVPlayerMuteCheckbox(). mediaspace == null")}}
function SetTVPlayerPauseCheckbox(){var a=document.getElementById("CheckboxTVPlayerPause");if(null!=a){var b=jwplayer("mediaspace1");if(b){var c=!1;"PAUSED"==b.getState()&&(c=!0);a.checked=c}else alert("ERROR: SetTVPlayerPauseCheckbox(). mediaspace == null")}}function ReloadTVChannel(){g_TVChannelID=get_cookie("TVChannel");null==g_TVChannelID||"0"==g_TVChannelID?document.getElementById("TVPlayerControl").style.display="none":getTVChannel(g_TVChannelID)}
function TVPlayerVolume(){var a=document.getElementById("TVPlayerVolume");if(null!=a){var b=jwplayer("mediaspace1");b?a.value=b.getVolume():alert("ERROR: TVPlayerVolume(). mediaspace == null")}}function TVPlayerSetVolume2(a){switch(g_TVPlayerType){case 0:var b=jwplayer("mediaspace1");if(!b){alert("ERROR: TVPlayerSetVolume2(Volume). mediaspace == null");break}b.setVolume(a);break;case 1:doVolume(a);break;case 2:break;default:ErrorMessage("Unknown g_TVPlayerType = "+g_TVPlayerType)}}
function TVPlayerSetVolume(a){}function SetTVPlayerStateToRC(){}function processReqTVPlayerStateToRC(){0!=g_reqTVPlayerStateToRC.readyState&&processReqChange1(g_reqTVPlayerStateToRC)}function processReqChangeRemoteTVPlayerGetState(){0!=g_reqRemoteTVPlayerGetState.readyState&&processReqChange1(g_reqRemoteTVPlayerGetState)};