var g_reqRemoteTVPlayerPause=null,g_reqRemoteTVPlayerMute=null,g_reqRemoteReloadTVChannel=null,g_reqRemoteTVPlayerVolume=null,g_knobClearance=0,g_knobWidth=5,g_imgWaitCircle='<img src="WaitGif\\WaitCircle.gif" style="width:16px; height:16px">',g_ButtonPrevTVChannelRCText="<",g_ButtonNextTVChannelRCText=">",g_ButtonReloadTVChannelRCText="Reload";function MyResize(){VolumeIndicators()}function TVPlayerGetStateRC(){}
function VolumeIndicators(){var a=document.getElementById("ButtonTVPlayerVolumeRC"),b=a.clientWidth,c=a.clientHeight;g_knobClearance=b/10-g_knobWidth;var d=document.getElementById("10_knob");if(!d||d.style.left!=parseInt(9*g_knobClearance)+"px"){d=c/10;for(i=1;10>=i;i++){var e=i+"_knob",f=document.getElementById(e);f||(f=document.createElement("div"),f.id=e,f.className="knobi",a.appendChild(f));f.style.width=g_knobWidth+"px";e=parseInt(c-d*i-2);f.style.top=e+"px";f.style.height=parseInt(c-e-4)+"px";
f.style.left=parseInt(g_knobClearance*(i-1))+"px"}a=get_cookie("Volume");if(null==a||"NaN"==a)a=50;TVPlayerVolumeRCX(parseInt(b*a/100)+1,b)}}
function TVPlayerVolumeRC(a){var b=0,c=0;if("undefined"==typeof event){if("undefined"==typeof a){alert("TVPlayerVolumeRC(e). e == 'undefined'");return}b=document.getElementById("ButtonTVPlayerVolumeRC");c=b.clientWidth;b=a.pageX-b.offsetLeft-g_knobWidth/2}else b=event.offsetX,c=event.srcElement.clientWidth,"knobi"==event.srcElement.className&&(c=event.srcElement.parentElement.clientWidth,b=(g_knobClearance+g_knobWidth)*parseInt(event.srcElement.id)-c/10+10);TVPlayerVolumeRCX(b,c)}
function TVPlayerVolumeRCX(a,b){var c=parseInt(100*a/b);for(i=1;10>=i;i++){var d=document.getElementById(i+"_knob");parseInt(d.style.left)+g_knobWidth*i+g_knobWidth/2>a?d.style.background="gray":d.style.background="black"}TVPlayerVolumeRCVolume(c)}
function TVPlayerVolumeRCVolume(a){""==g_guidRemote?ErrorMessage("TVPlayerVolumeRC("+a+") failed! g_guidRemote == ''"):(document.getElementById("info").innerHTML=a,SetCookie("Volume",a),null==g_reqRemoteTVPlayerVolume&&(g_reqRemoteTVPlayerVolume=loadXMLDoc1()),null==g_reqRemoteTVPlayerVolume?ErrorMessage("TVPlayerVolumeRC("+a+") failed! g_reqRemoteTVPlayerVolume == null"):(MessageElement(""),g_reqRemoteTVPlayerVolume.open("GET","XMLHttpRequest.srf?guidRemote="+g_guidRemote+"&mode=sound&volume="+a,
!0),g_reqRemoteTVPlayerVolume.onreadystatechange=processReqChangeRemoteTVPlayerVolume,g_reqRemoteTVPlayerVolume.send(null),DisableRCButtons()))}function processReqChangeRemoteTVPlayerVolume(){0!=g_reqRemoteTVPlayerVolume.readyState&&processReqChange1(g_reqRemoteTVPlayerVolume)}function DisableRCButtons(){return!1}
function Radio_onclick(a,b,c){if(""==b)ErrorMessage("Radio_onclick(...) failed! guidRemote == ''");else if(null==g_reqRemote&&(g_reqRemote=loadXMLDoc1()),null==g_reqRemote)ErrorMessage("Radio_onclick(...) failed! g_reqRemote == null");else{var d=null;if("undefined"==typeof this.event){if("undefined"==typeof c){alert("Radio_onclick(...). e == 'undefined'");return}d=c.target}else d=this.event.srcElement;if("radio"!=d.type)alert("type != radio");else{c=document.getElementsByName(d.name);for(i=0;i<c.length;i++)if(c[i].checked){d=
document.getElementById("ButtonReloadTVChannelRC");if(null==d){alert("Get ButtonReloadTVChannelRC element failed!");return}g_ButtonReloadTVChannelRCText=c[i].value;d.innerHTML=g_ButtonReloadTVChannelRCText;var d=-1,d=0==i?c.length-1:i-1,e=document.getElementById("ButtonPrevTVChannelRC");if(null==e){alert("Get ButtonPrevTVChannelRC element failed!");return}g_ButtonPrevTVChannelRCText="< "+c[d].value;e.innerHTML=g_ButtonPrevTVChannelRCText;d=i==c.length-1?0:i+1;e=document.getElementById("ButtonNextTVChannelRC");
if(null==e){alert("Get ButtonNextTVChannelRC element failed!");return}g_ButtonNextTVChannelRCText="> "+c[d].value;e.innerHTML=g_ButtonNextTVChannelRCText;break}MessageElement("");g_reqRemote.open("GET","XMLHttpRequestTVChannel.srf?guidRemote="+b+"&TVchannelID="+a,!0);g_reqRemote.onreadystatechange=processReqChangeRemote;g_reqRemote.send(null)}}}function processReqChangeRemote(){processReqChange1(g_reqRemote)}
function TVPlayerTVChannelRC(a){if(""==g_guidRemote)ErrorMessage("TVPlayerMuteRC() failed! g_guidRemote == ''");else{var b=-1,c="";IsFavorites()&&(c="F");c=document.getElementsByName("RadioGroupR"+c);if(0!=c.length){var d="";for(i=0;i<c.length;i++)if(c[i].checked)if("PrevTVChannel"==a){d="ButtonPrevTVChannelRC";b=0==i?c.length-1:i-1;break}else if("NextTVChannel"==a){d="ButtonNextTVChannelRC";b=i==c.length-1?0:i+1;break}else{alert("ERROR: Unknown TVChannel RC mode: "+a);return}-1==b&&(b=0);c[b].click();
if(""!=d){a=document.getElementById(d);if(null==a){ErrorMessage("Get elementButtonPrevTVChannelRC element failed!");return}a.innerHTML=g_imgWaitCircle}DisableRCButtons()}}}
function TVPlayerPauseRC(){if(""==g_guidRemote)ErrorMessage("TVPlayerPauseRC() failed! g_guidRemote == ''");else if(null==g_reqRemoteTVPlayerPause&&(g_reqRemoteTVPlayerPause=loadXMLDoc1()),null==g_reqRemoteTVPlayerPause)ErrorMessage("ReloadTVChannelRC(...) failed! g_reqRemoteTVPlayerPause == null");else{var a=document.getElementById("CheckboxTVPlayerPauseRC");null==a?ErrorMessage("Get CheckboxTVPlayerPauseRC element failed!"):(a.innerHTML=g_imgWaitCircle,MessageElement(""),g_reqRemoteTVPlayerPause.open("GET",
"XMLHttpRequest.srf?guidRemote="+g_guidRemote+"&mode=pause",!0),g_reqRemoteTVPlayerPause.onreadystatechange=processReqChangeRemoteTVPlayerPause,g_reqRemoteTVPlayerPause.send(null),DisableRCButtons())}}function processReqChangeRemoteTVPlayerPause(){0!=g_reqRemoteTVPlayerPause.readyState&&processReqChange1(g_reqRemoteTVPlayerPause)}
function TVPlayerMuteRC(){if(""==g_guidRemote)ErrorMessage("TVPlayerMuteRC() failed! g_guidRemote == ''");else if(null==g_reqRemoteTVPlayerMute&&(g_reqRemoteTVPlayerMute=loadXMLDoc1()),null==g_reqRemoteTVPlayerMute)ErrorMessage("ReloadTVChannelRC(...) failed! g_reqRemoteTVPlayerMute == null");else{var a=document.getElementById("CheckboxTVPlayerMuteRC");if(null==a)ErrorMessage("Get CheckboxTVPlayerMuteRC element failed!");else{a.innerHTML=g_imgWaitCircle;MessageElement("");DisableRCButtons();switch(g_reqRemoteTVPlayerMute.readyState){case 0:case 4:break;
default:return}g_reqRemoteTVPlayerMute.open("GET","XMLHttpRequest.srf?guidRemote="+g_guidRemote+"&mode=mute",!0);g_reqRemoteTVPlayerMute.onreadystatechange=processReqChangeRemoteTVPlayerMute;g_reqRemoteTVPlayerMute.send(null)}}}function processReqChangeRemoteTVPlayerMute(){0!=g_reqRemoteTVPlayerMute.readyState&&processReqChange1(g_reqRemoteTVPlayerMute)}
function TVPlayerRC(a){var b=0,c=document.getElementById("ButtonTVPlayerVolumeRC"),d="",b=Math.round(document.getElementById("info").innerHTML);"increase"==a?(d="ButtonTVPlayerIncreaseVolumeRC",4>b&&(b+=1),b=0==b?1:1.2*b):"decrease"==a&&(d="ButtonTVPlayerDecreaseVolumeRC",4>b?b-=1:1>b?b=0:0<b&&(b/=1.2));b=Math.round(b);100<b&&(b=100);1>b&&(b=0);a=document.getElementById(d);""==d||null==a?ErrorMessage("Set wait ButtonRC element failed!"):(a.innerHTML=g_imgWaitCircle,c=c.clientWidth,TVPlayerVolumeRCX(parseInt(c*
b/100)+1,c))}function processReqChangeRemoteTVPlayer(){0!=g_reqRemoteTVPlayer.readyState&&processReqChange1(g_reqRemoteTVPlayer)}
function ReloadTVChannelRC(){if(""==g_guidRemote)ErrorMessage("ReloadTVChannelRC() failed! g_guidRemote == ''");else if(null==g_reqRemoteReloadTVChannel&&(g_reqRemoteReloadTVChannel=loadXMLDoc1()),null==g_reqRemoteReloadTVChannel)ErrorMessage("ReloadTVChannelRC(...) failed! g_reqRemoteReloadTVChannel == null");else{var a=document.getElementById("ButtonReloadTVChannelRC");null==a?ErrorMessage("Get ButtonReloadTVChannelRC element failed!"):(a.innerHTML=g_imgWaitCircle,MessageElement(""),g_reqRemoteReloadTVChannel.open("GET",
"XMLHttpRequest.srf?guidRemote="+g_guidRemote+"&mode=reload",!0),g_reqRemoteReloadTVChannel.onreadystatechange=processReqChangeRemoteReloadTVChannel,g_reqRemoteReloadTVChannel.send(null),DisableRCButtons())}}function processReqChangeRemoteReloadTVChannel(){0!=g_reqRemoteReloadTVChannel.readyState&&processReqChange1(g_reqRemoteReloadTVChannel)}function Bandwidth(){SetCookie("Bandwidth",GetBandwidth());location.reload()}
function GetBandwidth(){var a=document.getElementById("bandwidth");if(null==a)alert("ERROR: bandwidth == null");else return a.checked}
function RestoreRCButtons(){var a=document.getElementById("ButtonPrevTVChannelRC");null==a?ErrorMessage("Get ButtonPrevTVChannelRC element failed!"):(a.innerHTML=g_ButtonPrevTVChannelRCText,a=document.getElementById("ButtonNextTVChannelRC"),null==a?ErrorMessage("Get ButtonNextTVChannelRC element failed!"):(a.innerHTML=g_ButtonNextTVChannelRCText,a=document.getElementById("ButtonReloadTVChannelRC"),null==a?ErrorMessage("Get ButtonReloadTVChannelRC element failed!"):(a.innerHTML=g_ButtonReloadTVChannelRCText,
a=document.getElementById("CheckboxTVPlayerPauseRC"),null==a?ErrorMessage("Get CheckboxTVPlayerPauseRC element failed!"):(a.innerHTML='<img src="img\\pause.png">',a=document.getElementById("CheckboxTVPlayerMuteRC"),null==a?ErrorMessage("Get CheckboxTVPlayerMuteRC element failed!"):(a.innerHTML='<img src="img\\mute.png">',a=document.getElementById("ButtonTVPlayerDecreaseVolumeRC"),null==a?ErrorMessage("Get ButtonTVPlayerDecreaseVolumeRC element failed!"):(a.innerHTML="-",a=document.getElementById("ButtonTVPlayerIncreaseVolumeRC"),
null==a?ErrorMessage("Get ButtonTVPlayerIncreaseVolumeRC element failed!"):a.innerHTML="+"))))))};